#!/bin/bash -e

ORG_PATH="github.com/oscarrr110"
REPO_PATH="${ORG_PATH}/cert-tools"

export GOPATH=${PWD}/gopath

rm -f $GOPATH/src/${REPO_PATH}
mkdir -p $GOPATH/src/${ORG_PATH}
ln -s ${PWD} $GOPATH/src/${REPO_PATH}

eval $(go env)

go build -o bin/cert-tools ${REPO_PATH}

